### ISSUE TITLE
Три краша IndexOutOfBoundsException на китайцах

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#109]
В DashboardFragment произошло:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
       at java.util.ArrayList.get(ArrayList.java:437)
       at java.util.Collections$UnmodifiableList.get(Collections.java:1356)
       at androidx.recyclerview.widget.ListAdapter.getItem(ListAdapter.java:2)
       at kekmech.ru.common_adapter.BaseAdapter.onViewDetachedFromWindow(BaseAdapter.java:2)
       at androidx.recyclerview.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:13)
       at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:10)
       at androidx.recyclerview.widget.ChildHelper.removeViewIfHidden(ChildHelper.java:7)
       at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:7)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:7)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:7)
       at androidx.recyclerview.widget.SimpleItemAnimator.dispatchMoveFinished(SimpleItemAnimator.java:1)
       at androidx.recyclerview.widget.DefaultItemAnimator$6.onAnimationEnd(DefaultItemAnimator.java:1)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1027)
       at android.view.Choreographer.doCallbacks(Choreographer.java:852)
       at android.view.Choreographer.doFrame(Choreographer.java:783)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:7441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Связано с адаптером.

**Comment by tonykolomeytsev** [comment]
Закрыто в версии 1.4.0
