### ISSUE TITLE
Краш приложения из-за UndeliverableException

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#146]
Как воспроизвести, пока не понял, вот логи:

В потоке Rx:
```
Fatal Exception: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | kekmech.ru.common_network.okhttp.NoInternetConnectionException: No internet connection!
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:2)
       at io.reactivex.rxjava3.internal.operators.single.SingleZipArray$ZipCoordinator.innerError(SingleZipArray.java:5)
       at io.reactivex.rxjava3.internal.operators.single.SingleZipArray$ZipSingleObserver.onError(SingleZipArray.java:4)
       at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:2)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onError(ObservableSingleSingle.java:13)
       at retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onError(BodyObservable.java:6)
       at retrofit2.adapter.rxjava3.CallEnqueueObservable$CallCallback.onFailure(CallEnqueueObservable.java:9)
       at retrofit2.OkHttpCall$1.callFailure(OkHttpCall.java:4)
       at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

В главном потоке:
```
kekmech.ru.common_network.okhttp.NoInternetConnectionException: No internet connection!
       at kekmech.ru.common_network.okhttp.NoConnectionInterceptor.intercept(NoConnectionInterceptor.java:4)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at kekmech.ru.common_network.okhttp.RequiredHeadersInterceptor.intercept(RequiredHeadersInterceptor.java:4)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:10)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by tonykolomeytsev** [comment]
Очень много падений на экране БАРСа

**Comment by tonykolomeytsev** [comment]
Пофиксил в ветке про новый кэш
