### ISSUE TITLE
Падение на Welcome экране, судя по всему

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#152]
Пиздец:

Из крашлитики:

```
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08008e
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:253)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:760)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
       at android.content.res.Resources.loadDrawable(Resources.java:886)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
       at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363)
       at android.widget.ImageView.<init>(ImageView.java:188)
       at android.widget.ImageView.<init>(ImageView.java:171)
```
![image](https://user-images.githubusercontent.com/18632470/133930459-ee4b5699-4237-433f-b140-4d1d26e86a47.png)

**Comment by tonykolomeytsev** [comment]
Один только вопрос, КАК?
Потому что там не вектор, там webp ресурс.
Android 8, Nexus 5

**Comment by tonykolomeytsev** [comment]
Походу вот так: https://stackoverflow.com/questions/54050456/resourcesnotfoundexception-on-splash-background-samsung-8-0-0-devices-only

**Comment by tonykolomeytsev** [comment]
Закрыто в хотфиске 1.10.2
