### ISSUE TITLE
IndexOutOfBoundsException во фрагменте DayFragment

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#73]
Вот такая штука в крашлитике (3 сбоя):
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{6947727 position=6 id=-1, oldPos=6, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{a060eb VFED..... ......I. 3240,0-4320,1770 #7f09007d app:id/dayFragmentRecyclerView}, adapter:b.a.e.f.a@2930e48, layout:androidx.recyclerview.widget.LinearLayoutManager@aa734e1, context:kekmech.ru.mainscreen.MainActivity@ea5c1a6
       at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:30)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:4)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.assertNotInLayoutOrScroll(RecyclerView.java)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:3)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:20)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:13)
       at androidx.recyclerview.widget.RecyclerView.d(RecyclerView.java:31)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:259)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:2)
       at com.google.android.material.appbar.ViewOffsetHelper.onViewLayout(ViewOffsetHelper.java)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:2)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:3)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:926)
       at android.view.View.layout(View.java:20960)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
Во фрагменте DayFragment ничего в UI не менялось, кроме добавления DiffUtil. Нужно в случае ошибки отрабатывания `DiffResult.dispatchUpdatesTo(Adapter)` просто делать `Adapter.notifyDataSetChanged()`. Скорее всего должно помочь.

**Comment by tonykolomeytsev** [comment]
Проблема с DiffUtil не только у меня, оказывается много у кого падает.
