### ISSUE TITLE
IllegalStateException в TimetableFragment

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#74]
Еще одно чудо из крашлитики. Как такие ошибки вообще происходят.
```
Fatal Exception: java.lang.IllegalStateException: viewPager must not be null
       at kekmech.ru.timetable.view.TimetableFragment.e(TimetableFragment.java:10)
       at kekmech.ru.timetable.TimetableFragmentPresenter$onResume$1$1.invokeSuspend(TimetableFragmentPresenter.java:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.a(BaseContinuationImpl.java:9)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by tonykolomeytsev** [comment]
Не актуально, расписания переписаны с нуля
