### ISSUE TITLE
Падение после запуска

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#95]
Стек:
```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f0800ab
       at android.content.res.Resources.getValue(Resources.java:1266)
       at android.content.res.Resources.getDrawable(Resources.java:785)
       at android.content.Context.getDrawable(Context.java:403)
       at android.view.View.setBackgroundResource(View.java:16207)
       at kekmech.ru.feature_onboarding.item.PromoPageViewHolderImpl.setIcon(PromoPageViewHolderImpl.java)
       at kekmech.ru.feature_onboarding.item.PromoPageBinder.bind(PromoPageBinder.java:3)
```

скорее всего из-за векторного изображения на WelcomeFragment'е в котором используется clip-path
Android 5.1

**Comment by tonykolomeytsev** [comment]
Должно быть пофикшено. Неподдерживаемый ресурс выпилен
